BLOCK_SITE: []
DATABASE: sqlite
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://imsun.pw/links/
  theme: volantis
- link: https://blog.sunpeiwen.com/links/
  theme: butterfly
MAX_POSTS_NUM: 10
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: false
  json_api: ''
  list: []
